lesson-14
DariaPavlyuk81/daria-pavlyuk-IO pull request #8
Opened 2024-08-24 14:20 UTC by DariaPavlyuk81

form and functionality added

2024-08-28 12:56 UTC, dindustack commented on index.html
> +        /><br />
Take of `/>`before the `<br />` tag

2024-08-28 19:39 UTC, dindustack commented on css/index.css
> +#message-list{
Update CSS styling for message-list

.message-list {
    list-style-type: none;
    padding: 0;
    margin: 0;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.message-list li span {
    display: block;
}

.message-list > .remove-button {
    background-color: #F00;
    color: #fff;
    border: 1px solid #F00;
    padding: 5px 10px;
    border-radius: 10px;
    cursor: pointer;
    font-size: 0.875;
    margin-left: 0.5rem;
}

2024-08-28 19:49 UTC, dindustack commented on js/index.js
> +const newMessage = document.createElement("li");
Add a class to li for styling

`newMessage.classList.add("message-list");`

2024-08-28 21:06 UTC, dindustack commented on js/index.js
> +//callback for remove button
remove button function should come under `FormSubmit`function

2024-08-28 21:10 UTC, dindustack commented on css/index.css
> +  margin:20px auto;
Add `display: none` to `#messages` styling

2024-08-28 21:10 UTC, dindustack requested changes
Improve the aesthetics of the form input CSS styling and review the corrections I made

2024-09-02 07:20 UTC, dindustack commented on css/index.css
> +  display: none;
Add the styling below to `#messages`

`border: 1px solid black`

2024-09-02 07:20 UTC, dindustack requested changes
The skills and connect and form sections are missing their styling.

Good work on the responsiveness.

2024-09-04 06:06 UTC, dindustack commented on js/index.js
> +//callback for remove button
Please, remove lines 107 - 118, there are two functionalities with the name `onRemoveButton`

2024-09-04 06:06 UTC, dindustack requested changes
I have left comments for correction

2024-09-04 09:32 UTC, DariaPavlyuk81 commented on js/index.js
> +//callback for remove button
ok, thank you

2024-09-04 10:41 UTC, dindustack requested changes
1. For the messages section, the content should be in a horizontal line, work on the CSS styling. 

2. For the form section, work on the CSS styling of the input field.

3. Remove empty lines of code

HTML (index.html)
1. Labels for Form Fields: Each form field should have a corresponding label. While you have included labels, ensure they are correctly associated with their respective form fields using the for attribute matching the input's id. For example, <label for="usersName">Users Name:</label> is correctly set, but make sure all labels follow this pattern.
Section Element Above Footer: The instructions required adding the new 'section' element above the 'footer' element. However, the footer is being added dynamically via JavaScript, which is not mentioned in the instructions. Consider modifying the structure in the HTML directly or adjusting the JavaScript to meet the specification.

JavaScript (index.js)

1. Variable Naming and Code Clarity: Use consistent and descriptive variable names. For instance, messageForm and messageForms[0] can be confusing. Simplify this by directly selecting the form using document.querySelector('[name="leave_message"]') to improve readability.

2024-09-04 20:47 UTC, merged